name: Run OptiSigns Scraper Daily

on:
  schedule:
    - cron: '0 6 * * *' # schedules to run every day at 6am UTC
  workflow_dispatch:     

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t optisigns-scraper .

      - name: Run Docker container
        run: |
          docker run \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            -e ZENDESK_SUBDOMAIN=${{ secrets.ZENDESK_SUBDOMAIN }} \
            optisigns-scraper
